from django.conf.urls import patterns, include, url

urlpatterns = patterns('',
    # get a dotfile for the referenced workflow 
    url(r'^(?P<workflow_slug>\w+)/dotfile/$', 'workflow.views.dotfile', name='dotfile'),
    # get a png image generated by graphviz for the referenced workflow 
    url(r'^(?P<workflow_slug>\w+).png$', 'workflow.views.graphviz', name='graphviz'),
)
